### ISSUE TITLE
add google analytics

### ISSUE THREAD

**Issue by ajdrake** [LouisvilleDataCommons/LouisvilleDataCommons.github.io#8]

**Comment by parkerduff** [comment]
I made a new branch and set up google analytics (and shared it with your gmail). This is the first time I have worked with google analytics, so I am not sure if I did it correctly. 
Also not sure whether to set up google tag manager https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-gtag
or google analytics https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-analytics

**Comment by ajdrake** [comment]
google tag manager helps you setup google analytics, so start with google tag manager first, and then do google analytics. that's how I understand it, but if you run into any issues or questions, let me know and I'm happy to help

**Comment by parkerduff** [comment]
I believe it is hooked up. You are also admin on the google analytics account, so configure it how you see fit

**Comment by ajdrake** [comment]
Awesome, thanks!
